name: aoc2023
description: Advent of Code 2023

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dart_numerics: ^0.0.6
  dio: ^5.4.0
  directed_graph: ^0.3.9
  equations: ^5.0.2
  file_saver: ^0.2.9
  fixnum: ^1.1.0
  flex_seed_scheme: ^1.4.0
  flutter:
    sdk: flutter
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.10
  flutter_helpers:
    git:
      url: https://bitbucket.org/magicwrighter/flutter-helpers/src/master/lib/flutter_helpers.dart
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  go_router: ^12.1.1
  google_fonts: ^6.1.0
  hooks_riverpod: ^2.4.9
  intl: ^0.19.0
  json_annotation: ^4.8.1
  matrix2d: ^1.0.4
  moment_dart: ^1.1.0
  number_to_words_english: ^2.0.2
  quantity: ^3.0.1
  retrofit: ^4.0.3
  riverpod_annotation: ^2.3.3
  uuid: ^4.2.1

dev_dependencies:
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  go_router_builder: ^2.3.4
  json_serializable: ^6.7.1
  lint: ^2.2.0
  retrofit_generator: ^8.0.5
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/data/
    - assets/images/
    - assets/images/icons/